name: Simple Workflow

on: workflow_dispatch

jobs:
  Myfirstjob:
    name: My first job
    runs-on: anjali
    steps:
      - name: Say Hello
        run: echo "Hello World!"
      # - name: Azure Login
      #   uses: Azure/login@v2.3.0
      #   with:
      #     client-id: 7b20495a-a14c-4ef2-bd11-222bf2538418
      #     tenant-id: af734fcf-6a49-4af5-8ec9-51df7466b2c5
      #     subscription-id: 95a90f4b-7e15-47ba-95ab-0d52bac078e4
   

        
       
                
